from typing import Optional, TypedDict, cast

import httpx

from stackoverflow_to_sqlite.types import QuestionResponse, ResponseWrapper

# https://api.stackexchange.com/2.3/users/474013/questions?pagesize=100&order=desc&sort=activity&site=math.stackexchange.com&filter=!OSaAEBD*BtuYwi(Zar.e4TBVOLdsyLhbieqkN9D*eGA
QUESTION_FILTER = "!OSaAEBD*BtuYwi(Zar.e4TBVOLdsyLhbieqkN9D*eGA"


def _api_call(
    path: str, site: str, filter_="", params: Optional[dict[str, str]] = None
) -> ResponseWrapper:
    assert path.startswith("/")
    response = httpx.get(
        f"https://api.stackexchange.com/2.3{path}",
        params={"pagesize": 100, "site": site, "filter": filter_, **(params or {})},
        headers={"user-agent": "stackoverflow-to-sqlite"},
    )
    response.raise_for_status()

    return response.json()


def fetch_questions(user_id: str, site: str) -> list[QuestionResponse]:
    return [
        {
            "tags": ["macros", "elixir"],
            "comments": [
                {
                    "owner": {
                        "account_id": 10360,
                        "reputation": 5788,
                        "user_id": 19520,
                        "user_type": "registered",
                        "display_name": "ema",
                        "link": "https://stackoverflow.com/users/19520/ema",
                    },
                    "post_id": 77357478,
                    "comment_id": 136380173,
                }
            ],
            "owner": {
                "account_id": 2045145,
                "reputation": 5204,
                "user_id": 1825390,
                "user_type": "registered",
                "display_name": "xavdid",
                "link": "https://stackoverflow.com/users/1825390/xavdid",
            },
            "is_answered": True,
            "view_count": 104,
            "favorite_count": 0,
            "down_vote_count": 0,
            "up_vote_count": 0,
            "accepted_answer_id": 77359032,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1698233092,
            "creation_date": 1698219631,
            "question_id": 77357478,
            "body_markdown": "I&#39;d like to define a subset of the cases in my `case` clause with a macro. Unfortunately, I&#39;m getting a syntax error. Here&#39;s what I have:\r\n\r\n```lang-elixir\r\ndefmodule Yacht do\r\n  @type category ::\r\n          :ones\r\n          | :twos\r\n          | :threes\r\n          | :fours\r\n          | :fives\r\n          | :sixes\r\n\r\n  defmacro count_case(dice, symbol, value) do\r\n    quote do\r\n      unquote(symbol) -&gt;\r\n        unquote(value) * Enum.count(unquote(dice), &amp;(&amp;1 == unquote(value)))\r\n    end\r\n  end\r\n\r\n  @doc &quot;&quot;&quot;\r\n  Calculate the score of 5 dice using the given category&#39;s scoring method.\r\n  &quot;&quot;&quot;\r\n  @spec score(category :: category(), dice :: [integer]) :: integer\r\n  def score(category, dice) do\r\n    case category do\r\n      # these cause syntax errors if uncommented\r\n      # count_case(dice, :ones, 1)\r\n      # count_case(dice, :twos, 2)\r\n\r\n      # these work as expected\r\n      :threes -&gt;\r\n        3 * Enum.count(dice, &amp;(&amp;1 == 3))\r\n\r\n      :fours -&gt;\r\n        4 * Enum.count(dice, &amp;(&amp;1 == 4))\r\n\r\n      :fives -&gt;\r\n        5 * Enum.count(dice, &amp;(&amp;1 == 5))\r\n\r\n      :sixes -&gt;\r\n        6 * Enum.count(dice, &amp;(&amp;1 == 6))\r\n    end\r\n  end\r\nend\r\n```\r\n\r\nThis gives the error at `:threes`:\r\n\r\n```\r\n** (SyntaxError) lib/yacht.ex:32: unexpected operator -&gt;. If you want to define multiple clauses, the first expression must use -&gt;. Syntax error before: &#39;-&gt;&#39;\r\n    (elixir 1.15.5) lib/kernel/parallel_compiler.ex:377: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8\r\n```\r\n\r\nI found [this forum thread](https://elixirforum.com/t/using-a-macro-to-generate-case-statements/3650) about defining cases with macros, but it recommends defining the entire case as syntax blocks and there are some extra cases not shown here that I don&#39;t want to do that with. \r\n\r\nSo. Is there a way to define a single `case` item with a macro?",
            "link": "https://stackoverflow.com/questions/77357478/is-it-possible-to-define-case-clauses-with-an-elixir-macro",
            "title": "Is it possible to define `case` clauses with an elixir macro?",
        },
        {
            "tags": ["go", "webserver", "benchmarking"],
            "owner": {
                "account_id": 2045145,
                "reputation": 5204,
                "user_id": 1825390,
                "user_type": "registered",
                "display_name": "xavdid",
                "link": "https://stackoverflow.com/users/1825390/xavdid",
            },
            "is_answered": False,
            "view_count": 148,
            "favorite_count": 0,
            "down_vote_count": 0,
            "up_vote_count": 3,
            "answer_count": 0,
            "score": 3,
            "last_activity_date": 1668281688,
            "creation_date": 1668281688,
            "question_id": 74415962,
            "body_markdown": "Broadly, I&#39;m trying to answer the question &quot;which of two approaches to handling incoming requests is more efficient&quot;. I&#39;m measuring efficiency by:\r\n\r\n- lower max RAM use\r\n- lower percentage of CPU usage\r\n\r\nThese metrics will _hopefully_ signal which approach is more suited to running on a resource-constrained server. It&#39;s gets a lot of volume, so the most important thing is that we can process requests faster than they come in. We&#39;ve had &quot;too many open files&quot; problems when our queue filled up and the server had too many open connections.\r\n\r\nSo, tach of the two programs aims to respond to the initial request as quickly as possible and then queue up the actual work. In real life, it&#39;s an outgoing HTTP request; in my tests, it&#39;s a `sleep` for a variable amount of time, to try to simulate inconsistent conditions. \r\n\r\nHere&#39;s the first program:\r\n\r\n```go\r\n// approach A: spin up a few goroutines at the start \r\n// and send messages into a long buffered channel\r\n\r\npackage main\r\n\r\nimport (\r\n\t&quot;fmt&quot;\r\n\t&quot;log&quot;\r\n\t&quot;math/rand&quot;\r\n\t&quot;net/http&quot;\r\n\t_ &quot;net/http/pprof&quot;\r\n\t&quot;time&quot;\r\n)\r\n\r\nconst (\r\n\tminResponseTimeSec = 0.5\r\n\tmaxResponeTimeSec  = 2.5\r\n)\r\n\r\nvar messageChan = make(chan int, 1024)\r\n\r\nfunc randResponseTime() float64 {\r\n\treturn minResponseTimeSec + rand.Float64()*(maxResponeTimeSec-minResponseTimeSec)\r\n}\r\n\r\nfunc main() {\r\n\trand.Seed(time.Now().UnixNano())\r\n\r\n\tfor i := 1; i &lt;= 8; i++ {\r\n\t\tgo worker()\r\n\t}\r\n\r\n\thttp.HandleFunc(&quot;/message&quot;, handler)\r\n\tlog.Fatal(http.ListenAndServe(&quot;:1234&quot;, nil))\r\n}\r\n\r\nfunc handler(writer http.ResponseWriter, request *http.Request) {\r\n\tmessageChan &lt;- 3 // would normally send POST body\r\n\tfmt.Fprint(writer, &quot;ok\\n&quot;)\r\n}\r\n\r\nfunc worker() {\r\n\tfor range messageChan {\r\n\t\ttime.Sleep(time.Second * time.Duration(randResponseTime()))\r\n\t}\r\n}\r\n```\r\n\r\nand here&#39;s the second:\r\n\r\n```go\r\n// approach B: set a maximum number of concurrent\r\n// goroutines and spin them up as needed\r\n\r\npackage main\r\n\r\nimport (\r\n\t&quot;fmt&quot;\r\n\t&quot;log&quot;\r\n\t&quot;math/rand&quot;\r\n\t&quot;net/http&quot;\r\n\t_ &quot;net/http/pprof&quot;\r\n\t&quot;time&quot;\r\n)\r\n\r\nconst (\r\n\tminResponseTimeSec = 0.5\r\n\tmaxResponeTimeSec  = 2.5\r\n)\r\n\r\nvar (\r\n\tsemaphoreChan chan struct{}\r\n)\r\n\r\nfunc randResponseTime() float64 {\r\n\treturn minResponseTimeSec + rand.Float64()*(maxResponeTimeSec-minResponseTimeSec)\r\n}\r\n\r\nfunc main() {\r\n\trand.Seed(time.Now().UnixNano())\r\n\r\n\tsemaphoreChan = make(chan struct{}, 1024)\r\n\r\n\thttp.HandleFunc(&quot;/message&quot;, handler)\r\n\tlog.Fatal(http.ListenAndServe(&quot;:1234&quot;, nil))\r\n}\r\n\r\nfunc handler(writer http.ResponseWriter, request *http.Request) {\r\n\tsemaphoreChan &lt;- struct{}{}\r\n\tgo fanout() // would normally send POST body\r\n\r\n\tfmt.Fprint(writer, &quot;ok\\n&quot;)\r\n}\r\n\r\nfunc fanout() {\r\n\tdefer func() { &lt;-semaphoreChan }()\r\n\ttime.Sleep(time.Second * time.Duration(randResponseTime()))\r\n}\r\n```\r\n\r\nWith each program running (separately) I used `ab` to send lots of requests at each in turn. But, I&#39;m having trouble interpreting the data available at `/profile/pprof`. I was focusing on the stats at the bottom of `/debug/pprof/heap?debug=1`, especially `TotalAlloc` and `HeapAlloc`. But, those numbers all seem to grow indefinitely (as I refresh the page), while I&#39;d expect them to stay flat before / after the benchmarking is done, which leads me to think I&#39;m looking at the wrong numbers.",
            "link": "https://stackoverflow.com/questions/74415962/how-to-benchmark-interpret-results-of-a-benchmark-a-go-webserver-under-load",
            "title": "How to benchmark (/interpret results of a benchmark) a Go webserver under load?",
        },
        {
            "tags": ["javascript", "node.js", "typescript", "npm"],
            "owner": {
                "account_id": 2045145,
                "reputation": 5204,
                "user_id": 1825390,
                "user_type": "registered",
                "display_name": "xavdid",
                "link": "https://stackoverflow.com/users/1825390/xavdid",
            },
            "is_answered": True,
            "view_count": 130,
            "favorite_count": 0,
            "down_vote_count": 0,
            "up_vote_count": 1,
            "accepted_answer_id": 39343549,
            "answer_count": 1,
            "score": 1,
            "last_activity_date": 1473148625,
            "creation_date": 1473123336,
            "question_id": 39339234,
            "body_markdown": "Say I write a node module, `m`. Later, I decide to add Typescript typings to it. Luckily, the module only exports a single function, so the m.d.ts file is as follows:\r\n\r\n    /// &lt;reference path=&quot;./typings/globals/node/index.d.ts&quot; /&gt;\r\n    \r\n    declare module &quot;m&quot; {\r\n      doThings(b: Buffer): int;\r\n    \r\n      export = doThings;\r\n    }\r\n\r\nMy function uses node&#39;s `Buffer`, so I included a valid reference to the node typings in the installed `typings` folder (without it, Sublime gives me the &quot;Cannot find name &#39;Buffer&#39; message, which seems like a bad thing). Everything looks good, so I update the `typings` key in my `package.json` and deploy. \r\n\r\nSeparately, I&#39;m using module `m` in a separate typescript project, `p`. I don&#39;t have to worry about using `typings`, since my module has types included. When I run `tsc`, I get the following error: `node_modules/m/m.d.ts(6,1): error TS6053: File &#39;/Users/$USER/projects/p/node_modules/m/typings/globals/node/index.d.ts&#39; not found.` That makes a lot of sense, since there isn&#39;t a `typings` folder in `node_modules` (I was under the impression checking generated folders like that was discouraged). When a typings file is loaded into DefinitelyTyped, it strips out all of the triple slash references (and the [best practices](https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html) say that you shouldn&#39;t include them in d.ts files). When there&#39;s a typings file loaded into an npm module, nothing is stripped out. \r\n\r\nSo, my question is this: can I have my cake and eat it too? Is it possible to have valid typings in my module (`m`) while not including broken references in external projects (`p`)? \r\n\r\nThanks a bunch!",
            "link": "https://stackoverflow.com/questions/39339234/if-im-adding-typings-to-an-npm-module-how-can-i-depend-on-global-typings",
            "title": "If I&#39;m adding typings to an npm module, how can I depend on global typings?",
        },
        {
            "tags": ["ios", "swift", "interface-builder"],
            "owner": {
                "account_id": 2045145,
                "reputation": 5204,
                "user_id": 1825390,
                "user_type": "registered",
                "display_name": "xavdid",
                "link": "https://stackoverflow.com/users/1825390/xavdid",
            },
            "is_answered": True,
            "view_count": 82,
            "favorite_count": 0,
            "down_vote_count": 0,
            "up_vote_count": 3,
            "accepted_answer_id": 33601506,
            "answer_count": 2,
            "score": 3,
            "last_activity_date": 1447258339,
            "creation_date": 1447034311,
            "question_id": 33601372,
            "body_markdown": "When the user taps on a text field, I wanted to darken the rest of the screen (everything below the text box, above the keyboard) to make it clear what they should be doing. I believe it involved putting a transparent UI view down and adding a gesture recognizer to it, but I&#39;m not quite sure how to do that. \r\n\r\nI&#39;ve got the following code for when the user arrives on the screen. Is this where I would add the new UI View?\r\n\r\n    override func viewWillAppear(animated: Bool) {\r\n      super.viewWillAppear(animated)\r\n      textField.becomeFirstResponder()\r\n    }\r\n\r\nThanks!",
            "link": "https://stackoverflow.com/questions/33601372/darkened-overlay-while-user-is-typing",
            "title": "Darkened overlay while user is typing",
        },
        {
            "tags": ["javascript", "jquery", "angularjs", "jquery-mobile"],
            "owner": {
                "account_id": 2045145,
                "reputation": 5204,
                "user_id": 1825390,
                "user_type": "registered",
                "display_name": "xavdid",
                "link": "https://stackoverflow.com/users/1825390/xavdid",
            },
            "is_answered": True,
            "view_count": 153,
            "favorite_count": 0,
            "down_vote_count": 0,
            "up_vote_count": 0,
            "accepted_answer_id": 28570411,
            "answer_count": 2,
            "score": 0,
            "last_activity_date": 1424204490,
            "creation_date": 1423881940,
            "question_id": 28511873,
            "body_markdown": "So I wanted to make a stopwatch app that had some extra sports tracking features built in. I&#39;m using this angular [timer](https://siddii.github.io/angular-timer/) library for the stopwatch (with copied-from-the-docs start and stop buttons), then adding text to a list with a button- pretty straightforward. \r\n\r\n    var app = angular.module(&#39;myTimer&#39;, [&#39;timer&#39;])\r\n\r\n    .controller(&#39;MainCtrl&#39;, [&#39;$scope&#39;, function($scope){\r\n      $scope.init = true;\r\n      $scope.timerRunning = false;\r\n\r\n      $scope.startTimer = function() {\r\n        // calling init on a running timer borks it\r\n        if ($scope.init) {\r\n          $scope.$broadcast(&#39;timer-start&#39;);\r\n          $scope.init = false;\r\n        }\r\n        else {\r\n          $scope.$broadcast(&#39;timer-resume&#39;);\r\n        }\r\n        $scope.timerRunning = true;  \r\n      };\r\n\r\n      $scope.stopTimer = function() {\r\n        $scope.$broadcast(&#39;timer-stop&#39;);\r\n        $scope.timerRunning = false;\r\n      };\r\n    }]);\r\n\r\nUnfortunately, loading the page over localhost on mobile (iPhone 5S, iOS 8.1) works, but there&#39;s about a half second delay between pressing the start/stop button and the timer reacting- not exactly a pleasant user experience.\r\n\r\nI also tried a jQuery [implementation](https://github.com/jylauril/jquery-runner) which ran faster, but still not as snappy as the same site on desktop (or the native timer, understandably). \r\n\r\nSo my question is this: is there any configuration of javascript I can do to make this run quickly? I haven&#39;t done any mobile app development, so completing this project web based would be ideal.\r\n\r\nThanks!",
            "link": "https://stackoverflow.com/questions/28511873/angularjs-stopwatch-is-unusably-slow-on-mobile",
            "title": "AngularJS Stopwatch is unusably slow on mobile",
        },
        {
            "tags": ["javascript", "angularjs", "node.js", "express"],
            "owner": {
                "account_id": 2045145,
                "reputation": 5204,
                "user_id": 1825390,
                "user_type": "registered",
                "display_name": "xavdid",
                "link": "https://stackoverflow.com/users/1825390/xavdid",
            },
            "is_answered": True,
            "view_count": 488,
            "favorite_count": 0,
            "down_vote_count": 0,
            "up_vote_count": 0,
            "answer_count": 3,
            "score": 0,
            "last_activity_date": 1505846148,
            "creation_date": 1421396951,
            "question_id": 27979880,
            "body_markdown": "I have a simple AngularJS app with a [plunkr here][1].\r\n\r\nI&#39;d like to put the app into server running expressjs. Everything seems to be working except the partials don&#39;t render and there&#39;s no error displayed.\r\n\r\nWhen I go to `localhost:3000/views/base.html` I see the correct page which means it&#39;s being served correctly by express. Clicking the links at the top of the page correctly changes the url. The thing that makes me think it&#39;s an AngularJS issue is that the {{teams}} binding in the layout is blank, like AngularJS isn&#39;t rendering it at all. \r\n\r\nThe express directory is: \r\n\r\n    server.js\r\n    views/\r\n     |- layout.jade\r\n    public/\r\n     |- javascripts\r\n      |- angularApp.js\r\n     |- views\r\n      |- base.html\r\n      |- check.html\r\n    routes/\r\n     |- index.js\r\n\r\nThe contents of the individual files are below.\r\n\r\nserver.js\r\n\r\n    // includes\r\n    \r\n    var express = require(&#39;express&#39;);\r\n    var path = require(&#39;path&#39;);\r\n    var bodyParser = require(&#39;body-parser&#39;);\r\n    var mongoose = require(&#39;mongoose&#39;);\r\n    \r\n    var routes = require(&#39;./routes/index&#39;);\r\n    \r\n    var app = express();\r\n    \r\n    // view engine setup\r\n    app.set(&#39;views&#39;, path.join(__dirname, &#39;views&#39;));\r\n    app.set(&#39;view engine&#39;, &#39;jade&#39;);\r\n    \r\n    app.use(bodyParser.json());\r\n    app.use(bodyParser.urlencoded({ extended: false }));\r\n    app.use(express.static(path.join(__dirname, &#39;public&#39;)));\r\n    \r\n    \r\n    app.use(&#39;/&#39;, routes);\r\n    \r\n    // error handlers\r\n    // this is all\r\n\r\n    // catch 404 and forward to error handler\r\n    app.use(function(req, res, next) {\r\n        var err = new Error(&#39;Not Found&#39;);\r\n        err.status = 404;\r\n        next(err);\r\n    });\r\n    \r\n    // development error handler\r\n    // will print stacktrace\r\n    if (app.get(&#39;env&#39;) === &#39;development&#39;) {\r\n        app.use(function(err, req, res, next) {\r\n            res.status(err.status || 500);\r\n            res.render(&#39;error&#39;, {\r\n                message: err.message,\r\n                error: err\r\n            });\r\n        });\r\n    }\r\n    \r\n    // production error handler\r\n    // no stacktraces leaked to user\r\n    app.use(function(err, req, res, next) {\r\n        res.status(err.status || 500);\r\n        res.render(&#39;error&#39;, {\r\n            message: err.message,\r\n            error: {}\r\n        });\r\n    });\r\n    \r\n    \r\n    module.exports = app;\r\n\r\nangularApp.js\r\n    \r\n    var app = angular.module(&#39;myApp&#39;, [&#39;ui.router&#39;])\r\n      .config([\r\n        &#39;$stateProvider&#39;,\r\n        &#39;$urlRouterProvider&#39;,\r\n        function($stateProvider, $urlRouterProvider){\r\n          $stateProvider\r\n            .state(&#39;home&#39;, {\r\n              url: &#39;/&#39;,\r\n              templateUrl: &quot;../views/base.html&quot;,\r\n              controller: &quot;MainCtrl&quot;\r\n            })\r\n            .state(&#39;check&#39;, {\r\n                url: &#39;/check&#39;,\r\n                templateUrl: &quot;../views/check.html&quot;,\r\n                controller: &quot;CheckCtrl&quot;\r\n            });\r\n    \r\n          $urlRouterProvider.otherwise(&#39;/&#39;);\r\n\r\n        }\r\n      ])\r\n      .controller(&#39;MainCtrl&#39;, [&#39;$scope&#39;, function($scope){\r\n        $scope.teams = &quot;this is main&quot;;\r\n      }])\r\n      .controller(&#39;CheckCtrl&#39;, [&#39;$scope&#39;, function($scope){\r\n        $scope.teams = &quot;this is check&quot;\r\n      }]);\r\n\r\nlayout.jade\r\n\r\n    doctype html(lang=&#39;en&#39;)\r\n    html\r\n      //- linked stylesheets, works fine\r\n      include ./partials/head.jade\r\n         \r\n      body(ng-app=&#39;myApp&#39;)\r\n        nav#big-bar.navbar(role=&#39;navigation&#39;)\r\n          .container-fluid\r\n            .navbar-header\r\n              a(ui-sref=&#39;home&#39;)\r\n                p.brand.navbar-brand Site.com\r\n                     \r\n            div\r\n              ul.nav.navbar-nav                       \r\n                li#check\r\n                  a(ui-sref=&#39;check&#39;) Check\r\n             \r\n        .mid\r\n          p  title here? {{teams}}\r\n          h2= title \r\n    \r\n          div(ui-view)\r\n    \r\n        //- linked js, no missing stuff errors\r\n        include ./partials/scripts.jade\r\n\r\nindex.js (routes)\r\n\r\n    var express = require(&#39;express&#39;);\r\n    var router = express.Router();\r\n    \r\n    router.get(&#39;/&#39;, function(req, res) {\r\n      res.render(&#39;layout&#39;, {title: &#39;Register or something&#39;});\r\n    });\r\n    \r\n    module.exports = router;\r\n\r\n\r\n  [1]: http://plnkr.co/edit/FVvdmTeVSxaqhbd27XFp",
            "link": "https://stackoverflow.com/questions/27979880/how-to-get-partials-to-show-when-using-ui-router-with-expressjs",
            "title": "How to get partials to show when using ui-router with expressjs?",
        },
        {
            "tags": ["ruby", "sinatra", "erb"],
            "owner": {
                "account_id": 2045145,
                "reputation": 5204,
                "user_id": 1825390,
                "user_type": "registered",
                "display_name": "xavdid",
                "link": "https://stackoverflow.com/users/1825390/xavdid",
            },
            "is_answered": False,
            "view_count": 41,
            "favorite_count": 0,
            "down_vote_count": 0,
            "up_vote_count": 0,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1401414202,
            "creation_date": 1401412568,
            "question_id": 23945575,
            "body_markdown": "I&#39;ve got a Sinatra app that displays a bunch of info queried from a database. Because of the format of the info returned (such as having and admin&#39;s id number, but not their name), I end up doing a lot of: \r\n\r\n    &lt;% admins.each do |admin| %&gt;\r\n      &lt;% users.select {|user| user.id == admin.id} %&gt;\r\n        &lt;%= &lt;li&gt; user.name &lt;/li&gt; %&gt;\r\n      &lt;% end %&gt;\r\n    &lt;% end %&gt;\r\n\r\nNested iterations take time and I was wondering if, for big lists, there&#39;s a reasonable performance difference between doing the code above or doing the heavy lifting in the controller and having a readymade list for the erb template.\r\n\r\nThanks a bunch!\r\n\r\n__edit:__ FWIW, the database in question is mongodb and the server is making a few database calls (from different collections) to present the information to the client.",
            "link": "https://stackoverflow.com/questions/23945575/for-intense-iteration-does-front-end-vs-back-end-matter",
            "title": "For intense iteration, does front-end vs back-end matter?",
        },
        {
            "tags": ["ruby", "bash", "sinatra", "zsh", "zshrc"],
            "owner": {
                "account_id": 2045145,
                "reputation": 5204,
                "user_id": 1825390,
                "user_type": "registered",
                "display_name": "xavdid",
                "link": "https://stackoverflow.com/users/1825390/xavdid",
            },
            "is_answered": True,
            "view_count": 56,
            "favorite_count": 0,
            "down_vote_count": 0,
            "up_vote_count": 0,
            "accepted_answer_id": 23506231,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1399419006,
            "creation_date": 1399418394,
            "question_id": 23506135,
            "body_markdown": "I&#39;m using `rerun` and `sinatra` enough that I wanted a nice alias so I could execute `rerun ruby X.rb` where X was the current directory (ie: `/Users/David/Documents/Projects/sample`=&gt;`rerun ruby sample.rb`). \r\n\r\nThe command I&#39;m using (adapted from [this](https://stackoverflow.com/questions/1371261/get-current-directory-name-without-full-path-in-bash-script) question) is `alias sin=&quot;rerun ruby ${PWD##*/}.rb&quot;`. When I use that, it says `ruby: No such file or directory -- David.rb (LoadError)` as if it was passed my user folder instead of the project folder. \r\n\r\nHowever, when I manually source my `.zshrc` (`alias sz=&quot;source ~/.zshrc&quot;`, which should be run on shell creation (and all my other aliases work fine, so I have no reason to believe it wouldn&#39;t be working)) and run `sin` again, it totally works as intended. \r\n\r\nAny ideas? I&#39;m pretty new at bash scripting. Also, I&#39;m using zsh if that&#39;s important.",
            "link": "https://stackoverflow.com/questions/23506135/passing-directory-name-into-ruby-run-statement",
            "title": "Passing Directory name into Ruby run statement",
        },
        {
            "tags": ["javascript", "jquery", "iframe", "xss"],
            "comments": [
                {
                    "owner": {
                        "account_id": 1244536,
                        "reputation": 50506,
                        "user_id": 1206267,
                        "user_type": "registered",
                        "display_name": "Ohgodwhy",
                        "link": "https://stackoverflow.com/users/1206267/ohgodwhy",
                    },
                    "post_id": 19287918,
                    "comment_id": 28560850,
                },
                {
                    "owner": {
                        "account_id": 2045145,
                        "reputation": 5204,
                        "user_id": 1825390,
                        "user_type": "registered",
                        "display_name": "xavdid",
                        "link": "https://stackoverflow.com/users/1825390/xavdid",
                    },
                    "post_id": 19287918,
                    "comment_id": 28560912,
                },
                {
                    "owner": {
                        "account_id": 1244536,
                        "reputation": 50506,
                        "user_id": 1206267,
                        "user_type": "registered",
                        "display_name": "Ohgodwhy",
                        "link": "https://stackoverflow.com/users/1206267/ohgodwhy",
                    },
                    "post_id": 19287918,
                    "comment_id": 28560933,
                },
                {
                    "owner": {
                        "account_id": 2045145,
                        "reputation": 5204,
                        "user_id": 1825390,
                        "user_type": "registered",
                        "display_name": "xavdid",
                        "link": "https://stackoverflow.com/users/1825390/xavdid",
                    },
                    "post_id": 19287918,
                    "comment_id": 28561006,
                },
            ],
            "owner": {
                "account_id": 2045145,
                "reputation": 5204,
                "user_id": 1825390,
                "user_type": "registered",
                "display_name": "xavdid",
                "link": "https://stackoverflow.com/users/1825390/xavdid",
            },
            "is_answered": False,
            "view_count": 149,
            "favorite_count": 0,
            "down_vote_count": 0,
            "up_vote_count": 0,
            "closed_date": 1448182440,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1381383787,
            "creation_date": 1381383787,
            "question_id": 19287918,
            "body_markdown": "I&#39;m trying to implement a simple XSS attack for a (non-malicious) proof of concept and am having some issues. The goal is to populate a form and submit it within an iframe.\r\n\r\n    function grab() {\r\n        alert(&#39;yess&#39;);\r\n    };\r\n    \r\n    function makeLink() { \r\n        return &quot;http://mysite.com/?&quot; + encodeURIComponent(&quot;&lt;script&quot; + &quot;&gt;&quot; + grab.toString() +\r\n        &quot;;grab();&lt;/script&quot; + &quot;&gt;&quot;); \r\n        // returns &quot;http://mysite.com/?%3Cscript%3Efunction%20grab()%20%7B%0A%20%20%20%20alert(&#39;yess&#39;)%3B%0A%7D%3Bgrab()%3B%3C%2Fscript%3E&quot;\r\n    }\r\n\r\n    var iframe = document.createElement(&#39;iframe&#39;);\r\n    iframe.src = makeLink(xssdefense, target, attacker);\r\n    iframe.height = 600;\r\n    iframe.width = 800;\r\n    // not sure if I need this line, but un-commenting doesn&#39;t seem to change anything. \r\n    // iframe.sandbox = &quot;allow-scripts allow-same-origin allow-forms&quot;\r\n    document.body.appendChild(iframe);\r\n\r\n\r\nIdeally when this html file is opened, an iframe with the javascript injected will be sitting there. Upon console investigation, grab() is defined and callable in the main window, but not in the frame, which puzzles me.\r\n\r\nAnyway, any help is appreciated. Thanks a bunch!",
            "link": "https://stackoverflow.com/questions/19287918/implementing-an-xss-attack",
            "closed_reason": "Duplicate",
            "title": "Implementing an XSS attack",
        },
        {
            "tags": ["javascript", "html", "ruby-on-rails", "ajax", "jquery"],
            "owner": {
                "account_id": 2045145,
                "reputation": 5204,
                "user_id": 1825390,
                "user_type": "registered",
                "display_name": "xavdid",
                "link": "https://stackoverflow.com/users/1825390/xavdid",
            },
            "is_answered": True,
            "view_count": 2523,
            "favorite_count": 0,
            "down_vote_count": 0,
            "up_vote_count": 1,
            "accepted_answer_id": 17904477,
            "answer_count": 2,
            "score": 1,
            "last_activity_date": 1375030305,
            "creation_date": 1374978804,
            "question_id": 17904441,
            "body_markdown": "I&#39;m trying to let users import an OPML file that I parse server (rails app) side. I&#39;m having trouble as it seems that my server isn&#39;t getting the info (neither the success nor error functions run and even if I hardcode other data into the call, the call doesn&#39;t change). \r\n\r\nHere&#39;s what I have embedded into the page:\r\n\r\n    &lt;script&gt;\r\n    function handleFileSelect(evt) {\r\n          var files = evt.target.files; // FileList object\r\n    \r\n          // Loop through the FileList\r\n          for (var i = 0, f; f = files[i]; i++) {\r\n    \r\n            var reader = new FileReader();\r\n    \r\n            // Closure to capture the file information.\r\n            reader.onload = (function(theFile) {\r\n              return function(e) {\r\n                // Print the contents of the file\r\n                var span = document.createElement(&#39;span&#39;);                    \r\n                span.innerHTML = [&#39;&lt;p&gt;&#39;,e.target.result,&#39;&lt;/p&gt;&#39;].join(&#39;&#39;);\r\n                document.getElementById(&#39;list&#39;).insertBefore(span, null);\r\n              };\r\n    \r\n              $.ajax({\r\n                type: &#39;GET&#39;,\r\n                url: &quot;/parse_opml&quot;,\r\n                data: {file: f},\r\n                success: function(details, response) {\r\n                  console.log(&#39;woo!&#39;);\r\n                },\r\n                error: function(data, response) {\r\n                  console.log(&#39;boooo&#39;);\r\n                }\r\n              });\r\n            })(f);\r\n    \r\n            // Read in the file\r\n            reader.readAsText(f);\r\n          }\r\n        }\r\n    \r\n        document.getElementById(&#39;the_o&#39;).addEventListener(&#39;change&#39;, handleFileSelect, false);\r\n    &lt;/script&gt;\r\n\r\n    &lt;input id=&quot;the_o&quot; name=&quot;files[]&quot; type=&quot;file&quot;&gt;\r\n\r\nLooking at chrome&#39;s network panel, I&#39;m seeing the call: `Request URL:blob:http%3A//localhost%3A3000/14e2be6b-059f-47f5-ba37-97eda06242b4` whose preview and response is the content of my .txt file. But like I said, the server never gets that text, so I&#39;m puzzled. \r\n\r\nAny help is greatly appreciated, thanks!\r\n\r\n\r\n**ANSWER**\r\n\r\nI ended up just using this: https://stackoverflow.com/questions/5587973/javascript-upload-file\r\n\r\nClient code: \r\n\r\n    %form{:enctype =&gt; &#39;multipart/form-data&#39;, :action =&gt; &#39;/parse_opml&#39;, :method =&gt; &#39;post&#39;}\r\n       %input{:type =&gt; &#39;file&#39;, :name =&gt; &#39;file&#39;, :id =&gt; &#39;the_o&#39;}\r\n       %input{:type =&gt; &#39;submit&#39;, :value =&gt; &#39;go&#39;}\r\n\r\nServer code:\r\n\r\n    f = File.open(params[:file].tempfile, &#39;r&#39;)\r\n    c = f.read\r\n\r\n\r\nWorks like a charm!",
            "link": "https://stackoverflow.com/questions/17904441/how-can-i-send-the-contents-of-a-file-to-my-server",
            "title": "How can I send the contents of a file to my server?",
        },
        {
            "tags": ["javascript", "firefox", "firefox-addon", "firefox-addon-sdk"],
            "comments": [
                {
                    "owner": {
                        "account_id": 902274,
                        "reputation": 345736,
                        "user_id": 938089,
                        "user_type": "registered",
                        "display_name": "Rob W",
                        "link": "https://stackoverflow.com/users/938089/rob-w",
                    },
                    "post_id": 17412921,
                    "comment_id": 25287330,
                }
            ],
            "owner": {
                "account_id": 2045145,
                "reputation": 5204,
                "user_id": 1825390,
                "user_type": "registered",
                "display_name": "xavdid",
                "link": "https://stackoverflow.com/users/1825390/xavdid",
            },
            "is_answered": True,
            "view_count": 106,
            "favorite_count": 0,
            "down_vote_count": 0,
            "up_vote_count": 0,
            "accepted_answer_id": 17413070,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1372710418,
            "creation_date": 1372709884,
            "question_id": 17412921,
            "body_markdown": "I recently wrote a chrome extension and have been trying to port it into Firefox. \r\n\r\nIn chrome, you could use the full JS console to examine and mess with your (under development) extension, making bugfixing easy. Firefox (and firebug) don&#39;t seem to offer the same functionality. \r\n\r\nHere&#39;s my code so far: \r\n\r\nmain.js:\r\n\r\n    var widgets = require(&quot;sdk/widget&quot;);\r\n    var tabs = require(&quot;sdk/tabs&quot;);\r\n    var data = require(&quot;sdk/self&quot;).data;\r\n    \r\n    var bmpanel = require(&quot;sdk/panel&quot;).Panel({\r\n      width: 450,\r\n      height: 300,\r\n      contentURL: data.url(&quot;bookmarklet.html&quot;),\r\n      // contentScriptFile: data.url(&quot;get-text.js&quot;)\r\n    });\r\n    \r\n    var widget2 = require(&quot;sdk/widget&quot;).Widget({\r\n      id: &quot;my-widget&quot;,\r\n      label: &quot;Add to site!&quot;,\r\n      contentURL: &quot;icon.png&quot;,\r\n      panel: bmpanel\r\n    });\r\n\r\nbookmarklet.html is a simple page with some inline javascript (references, so it plays nice with chrome). \r\n\r\nI&#39;m using cfx so I can develop locally and reuse files, but there&#39;s a chance this isn&#39;t the best way to go about it. \r\n\r\nAny help is appreciated, thanks a bunch!\r\n\r\n",
            "link": "https://stackoverflow.com/questions/17412921/is-there-any-way-to-examine-add-on-using-the-js-console-in-firefox",
            "title": "Is there any way to examine add-on using the js console in Firefox?",
        },
        {
            "tags": ["javascript", "ruby-on-rails", "web", "bookmarklet"],
            "comments": [
                {
                    "owner": {
                        "account_id": 2682405,
                        "reputation": 16536,
                        "user_id": 2317490,
                        "user_type": "registered",
                        "display_name": "dandavis",
                        "link": "https://stackoverflow.com/users/2317490/dandavis",
                    },
                    "post_id": 17219649,
                    "comment_id": 24946477,
                }
            ],
            "owner": {
                "account_id": 2045145,
                "reputation": 5204,
                "user_id": 1825390,
                "user_type": "registered",
                "display_name": "xavdid",
                "link": "https://stackoverflow.com/users/1825390/xavdid",
            },
            "is_answered": True,
            "view_count": 151,
            "favorite_count": 0,
            "down_vote_count": 0,
            "up_vote_count": 0,
            "accepted_answer_id": 17224567,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1371765438,
            "creation_date": 1371747987,
            "question_id": 17219649,
            "body_markdown": "I&#39;m trying to write a bookmarklet that takes the site the user is on, does some parsing and an ajax request, and opens a new window with that info as a param. \r\n\r\nHere&#39;s what I&#39;ve got: \r\n\r\n    &lt;a href=&quot;javascript:\r\n    (function($) \r\n    {\r\n      var a, http, options, request, st, u;\r\n\r\n      u = document.location.hostname;\r\n\r\n      a = u.split(&#39;.&#39;);\r\n\r\n      st = a[a.length - 2];\r\n      path = &#39;http://ajax.googleapis.com/ajax/services/feed/find?callback=?&amp;v=1.0&amp;q=&#39; + st;\r\n      $.ajax\r\n      ({\r\n        type: &#39;GET&#39;,\r\n        url: path,\r\n        async: false,\r\n    dataType: &#39;json&#39;,\r\n    success: function(data)\r\n    {   \r\n      var targ  = data[&#39;responseData&#39;][&#39;entries&#39;][0][&#39;url&#39;];\r\n      window.open (&#39;http://localhost:3000/bmfeed?targ=&#39;+targ,&#39;menubar=1,resizable=1,width=350,height=250&#39;);\r\n    }\r\n      });\r\n    })(jQuery)\r\n\r\n    &quot;&gt; newwindow &lt;/a&gt;\r\n\r\nIt finds the right url, but the new window is blocked by the popup blocker. \r\n\r\nIf instead I just have \r\n\r\n    &lt;a href=&#39;javascript: window.open (&quot;http://localhost:3000?targ=asdfasdf&quot;,&quot;mywindow&quot;,&quot;menubar=1,resizable=1,width=350,height=250&quot;);&#39;&gt; oneline &lt;/a&gt;\r\n\r\nit opens a new tab uninhibited. I assume that the difference is that i&#39;m doing some parsing in the first example, which the browser doesn&#39;t like. \r\n\r\nIs there a way to have my cake and eat it too? Thanks a bunch!\r\n",
            "link": "https://stackoverflow.com/questions/17219649/bookmarklet-window-gets-blocked-if-i-try-to-do-anything-besides-open-a-new-windo",
            "title": "Bookmarklet window gets blocked if I try to do anything besides open a new window",
        },
        {
            "tags": ["c++", "error-handling", "cin"],
            "comments": [
                {
                    "owner": {
                        "account_id": 932526,
                        "reputation": 61340,
                        "user_id": 962089,
                        "user_type": "registered",
                        "display_name": "chris",
                        "link": "https://stackoverflow.com/users/962089/chris",
                    },
                    "post_id": 15801453,
                    "comment_id": 22470908,
                },
                {
                    "owner": {
                        "account_id": 2045145,
                        "reputation": 5204,
                        "user_id": 1825390,
                        "user_type": "registered",
                        "display_name": "xavdid",
                        "link": "https://stackoverflow.com/users/1825390/xavdid",
                    },
                    "post_id": 15801453,
                    "comment_id": 22470945,
                },
                {
                    "owner": {
                        "account_id": 932526,
                        "reputation": 61340,
                        "user_id": 962089,
                        "user_type": "registered",
                        "display_name": "chris",
                        "link": "https://stackoverflow.com/users/962089/chris",
                    },
                    "post_id": 15801453,
                    "comment_id": 22471132,
                },
                {
                    "owner": {
                        "account_id": 2045145,
                        "reputation": 5204,
                        "user_id": 1825390,
                        "user_type": "registered",
                        "display_name": "xavdid",
                        "link": "https://stackoverflow.com/users/1825390/xavdid",
                    },
                    "post_id": 15801453,
                    "comment_id": 22471831,
                },
                {
                    "owner": {
                        "account_id": 932526,
                        "reputation": 61340,
                        "user_id": 962089,
                        "user_type": "registered",
                        "display_name": "chris",
                        "link": "https://stackoverflow.com/users/962089/chris",
                    },
                    "post_id": 15801453,
                    "comment_id": 22472176,
                },
                {
                    "owner": {
                        "account_id": 2045145,
                        "reputation": 5204,
                        "user_id": 1825390,
                        "user_type": "registered",
                        "display_name": "xavdid",
                        "link": "https://stackoverflow.com/users/1825390/xavdid",
                    },
                    "post_id": 15801453,
                    "comment_id": 22472203,
                },
                {
                    "owner": {
                        "account_id": 932526,
                        "reputation": 61340,
                        "user_id": 962089,
                        "user_type": "registered",
                        "display_name": "chris",
                        "link": "https://stackoverflow.com/users/962089/chris",
                    },
                    "post_id": 15801453,
                    "comment_id": 22472283,
                },
                {
                    "owner": {
                        "account_id": 932526,
                        "reputation": 61340,
                        "user_id": 962089,
                        "user_type": "registered",
                        "display_name": "chris",
                        "link": "https://stackoverflow.com/users/962089/chris",
                    },
                    "post_id": 15801453,
                    "comment_id": 22472378,
                },
            ],
            "owner": {
                "account_id": 2045145,
                "reputation": 5204,
                "user_id": 1825390,
                "user_type": "registered",
                "display_name": "xavdid",
                "link": "https://stackoverflow.com/users/1825390/xavdid",
            },
            "is_answered": False,
            "view_count": 123,
            "favorite_count": 0,
            "down_vote_count": 0,
            "up_vote_count": 0,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1365042128,
            "creation_date": 1365041803,
            "question_id": 15801453,
            "body_markdown": "So I&#39;m reding input through cin in this while loop:\r\n\r\n    while (getline(cin,s))\r\n    {\r\n        cin &gt;&gt; name;\r\n        if (!cin)\r\n            exit(1);\r\n        \r\n        cin &gt;&gt; age;\r\n        in (!cin)\r\n            exit(1);\r\n    }\r\nto read a file for a project (there are more cin statements, but it&#39;s all the same little code bit). Unfortunately, it&#39;s required we use cin (not fstream) and exit(1) upon hitting malformed input. The problem with this is that when I hit a blank line at the end of a file, cin sees it as bad and exits when it shouldn&#39;t. \r\n\r\nAny ideas? \r\n\r\nThanks much. \r\n\r\n__edit__ the file looks like this:\r\n\r\nName Age Job $Salary \r\n\r\n    John 55 Worker $55 \r\n    Bob 23 Boxer $23 \r\n    Susie 26 Secretary $77 \r\n \r\netc",
            "link": "https://stackoverflow.com/questions/15801453/cin-is-checking-for-malformed-input-but-also-now-crashes-on-eof",
            "title": "cin is checking for malformed input, but also now crashes on EOF",
        },
        {
            "tags": ["c++", "macos", "gcc", "macports"],
            "comments": [
                {
                    "owner": {
                        "user_type": "does_not_exist",
                        "display_name": "user529758",
                    },
                    "post_id": 14495138,
                    "comment_id": 20201463,
                },
                {
                    "owner": {
                        "account_id": 1392510,
                        "reputation": 65774,
                        "user_id": 1322972,
                        "user_type": "registered",
                        "display_name": "WhozCraig",
                        "link": "https://stackoverflow.com/users/1322972/whozcraig",
                    },
                    "post_id": 14495138,
                    "comment_id": 20201707,
                },
            ],
            "owner": {
                "account_id": 2045145,
                "reputation": 5204,
                "user_id": 1825390,
                "user_type": "registered",
                "display_name": "xavdid",
                "link": "https://stackoverflow.com/users/1825390/xavdid",
            },
            "is_answered": False,
            "view_count": 296,
            "favorite_count": 0,
            "down_vote_count": 0,
            "up_vote_count": 0,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1674022793,
            "creation_date": 1359008475,
            "question_id": 14495138,
            "body_markdown": "I&#39;ve been using command line tools and a text editor to compile class projects, which has worked great. Unfortunately, they&#39;ve become sticklers about us using 4.7. Xcode (and thus OSX) only has llvm-gcc 4.2, so I was looking to upgrade. \r\n\r\nI&#39;ve got macports installed and have found instructions for installing gcc 4.7, but it says that I need xcode installed. I was hoping to be able to just use command line tools and not have xcode (I don&#39;t need any of the iOS or graphics stuff, I just want gcc. \r\n\r\nAnyway, if it&#39;s not possible, it&#39;s no big deal, but I&#39;d be appreciative if anyone could point me in the right direction. Thanks!\r\n\r\nTo clarify, I have command line tools, but not the version of gcc I&#39;d like. Running macports results in this:\r\n\r\n    $ sudo port install gcc47\r\n    Error: \r\n    Error: No Xcode installation was found.\r\n    Error: Please install Xcode and/or run xcode-select to specify its location.\r\n    Error: \r\n    Error: The installed version of Xcode (2.0orlower) is too old to use on the installed OS version. \r\n    Version 4.1 or later is recommended on Mac OS X 10.8.",
            "link": "https://stackoverflow.com/questions/14495138/can-i-use-gcc-4-7-and-c11-on-mountain-lion-without-installing-xcode",
            "title": "Can I use gcc 4.7 (and C++11) on Mountain Lion without installing XCode?",
        },
        {
            "tags": ["python", "inheritance"],
            "comments": [
                {
                    "owner": {
                        "account_id": 246741,
                        "reputation": 42654,
                        "user_id": 521034,
                        "user_type": "registered",
                        "display_name": "Keith",
                        "link": "https://stackoverflow.com/users/521034/keith",
                    },
                    "post_id": 13390201,
                    "comment_id": 18289522,
                },
                {
                    "owner": {
                        "account_id": 2045145,
                        "reputation": 5204,
                        "user_id": 1825390,
                        "user_type": "registered",
                        "display_name": "xavdid",
                        "link": "https://stackoverflow.com/users/1825390/xavdid",
                    },
                    "post_id": 13390201,
                    "comment_id": 18289546,
                },
                {
                    "owner": {
                        "account_id": 246741,
                        "reputation": 42654,
                        "user_id": 521034,
                        "user_type": "registered",
                        "display_name": "Keith",
                        "link": "https://stackoverflow.com/users/521034/keith",
                    },
                    "post_id": 13390201,
                    "comment_id": 18289558,
                },
                {
                    "owner": {
                        "account_id": 2045145,
                        "reputation": 5204,
                        "user_id": 1825390,
                        "user_type": "registered",
                        "display_name": "xavdid",
                        "link": "https://stackoverflow.com/users/1825390/xavdid",
                    },
                    "post_id": 13390201,
                    "comment_id": 18289571,
                },
                {
                    "owner": {
                        "account_id": 231940,
                        "reputation": 91831,
                        "user_id": 496445,
                        "user_type": "registered",
                        "display_name": "jdi",
                        "link": "https://stackoverflow.com/users/496445/jdi",
                    },
                    "post_id": 13390201,
                    "comment_id": 18289592,
                },
            ],
            "owner": {
                "account_id": 2045145,
                "reputation": 5204,
                "user_id": 1825390,
                "user_type": "registered",
                "display_name": "xavdid",
                "link": "https://stackoverflow.com/users/1825390/xavdid",
            },
            "is_answered": True,
            "view_count": 180,
            "favorite_count": 0,
            "down_vote_count": 0,
            "up_vote_count": 2,
            "accepted_answer_id": 13390240,
            "answer_count": 1,
            "score": 2,
            "last_activity_date": 1352942755,
            "creation_date": 1352942429,
            "question_id": 13390201,
            "body_markdown": "Long time reader, first time asker. Anyway, Here&#39;s the code I&#39;m working with:\r\n\r\n    class Person(object):\r\n\t  def __init__(self, s):\r\n\t\tself.name = s\r\n\t\tself.secret = &#39;I HAVE THE COOKIES&#39;\r\n\r\n\t  @classmethod\r\n\t  def shout(self):\r\n\t\tprint self.name.upper()\r\n\r\n    class Kid(Person):\r\n\t  def __init__(self, s):\r\n\t\tsuper(Kid,self).__init__(s)\r\n\t\tself.age = 12\r\n\r\n    b = Person(&#39;Bob&#39;)\r\n    k = Kid(&#39;Bobby&#39;)\r\n    print b.name\r\n    print k.name\r\n    print k.age\r\n    print k.secret\r\n    k.shout()\r\nWhich results in this output and error:\r\n\r\n    Bob\r\n    Bobby\r\n    12\r\n    I HAVE THE COOKIES\r\n    Traceback (most recent call last):\r\n    File &quot;a.py&quot;, line 22, in &lt;module&gt;\r\n      k.shout()\r\n    File &quot;a.py&quot;, line 8, in shout\r\n      print self.name.upper()\r\n    AttributeError: type object &#39;Kid&#39; has no attribute &#39;name&#39;\r\n\r\nI assumed that Kid would be able to use the Person&#39;s shout method substituting its (the kid&#39;s) &quot;self&quot; for parent (where the method lives). Apparently, that&#39;s not the case. I know I could declare name outside of init, but that&#39;s both unable to accomodate inputted data and a no-no. Another alternative would be to redefine shout for every child of Person, but that&#39;s a lot of repeated code that I&#39;m trying to avoid. \r\n\r\nThanks very much in advance!",
            "link": "https://stackoverflow.com/questions/13390201/how-can-i-get-child-classes-to-use-parent-variables-without-redefining-them",
            "title": "How can I get child classes to use parent variables without redefining them?",
        },
    ]

    # TODO: loop
    return _api_call(
        f"/users/{user_id}/questions",
        site,
        filter_=QUESTION_FILTER,
        params={"order": "desc", "sort": "creation"},
    )
